// <auto-generated />
namespace BlogRepository_MySQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addClickCount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addClickCount));
        
        string IMigrationMetadata.Id
        {
            get { return "201903140425240_addClickCount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
